language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - export PYTHONPATH=.
script: django-admin.py test tempus --settings=tempus.tests.settings
